dist: xenial

language: python

python:
  - "3.7"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='python3.7' BUILD_PATH='python3.7' TEST_STR1='Hello World from a default Nginx uWSGI Python 3.7 app in a Docker container (default)' TEST_STR2='Hello World from Nginx uWSGI Python 3.7 app in a Docker container' RUN_TESTS='1'
  - NAME='latest' BUILD_PATH='python3.7' TEST_STR1='Hello World from a default Nginx uWSGI Python 3.7 app in a Docker container (default)' TEST_STR2='Hello World from Nginx uWSGI Python 3.7 app in a Docker container' RUN_TESTS='1'

script: bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
