dist: bionic

language: python

python:
  - "3.7"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='latest' BUILD_PATH='python3.7' TEST_STR1='Hello, World! This is the default message of a nginx uWSGI python 3.7 app deployed in a Docker container' TEST_STR2='Hello, World! Custom Python 3.7 App overriding default app for Testing' RUN_TESTS='1'

script: bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
